Repository infrastructure-io/topohub, pull requests merged in 2025-04, with the labels that each got.

#99 robot updates Golang Version to 1.24.2
  .github/workflows/lint-golang.yaml
  GO_VERSION
  go.mod
  image/topohub/Dockerfile
Labels: pr/robot_update

#96 add e2e check
  .github/workflows/auto-pr-ci.yaml
  .github/workflows/call-e2e.yaml
  .github/workflows/call-trivy.yaml
  chart/templates/deployment.yaml
Labels: release/none

#100 fix the incomplete log information
  pkg/redfish/log.go
Labels: release/bug

#105 Support retrieving resetTypes from the ResetActionInfo URL interface
  pkg/redfish/getinfo.go
Labels: enhancement, release/feature-new

#102 fix conflict between subnet network and host network
  Makefile.def
  pkg/subnet/dhcpserver/interface.go
  pkg/tools/tools.go
  pkg/webhook/subnet/webhook.go
  test/Makefile
  test/scripts/install-topohub.sh
Labels: release/bug
