Repository infrastructure-io/topohub, pull requests merged in 2025-05, with the labels that each got.

#104 fix IPRange check error
  .github/workflows/lint-golang.yaml
  chart/crds/topohub.infrastructure.io_subnets.yaml
  pkg/k8s/apis/topohub.infrastructure.io/v1beta1/subnet_types.go
Labels: release/bug

#106 update subnet dhcp clients info
  pkg/subnet/dhcpserver/UpdateSubnet.go
Labels: enhancement, release/none

#107 pxeReboot supports multiple reboot operations
  pkg/redfish/power.go
Labels: enhancement, release/none

#108 fix: it doest not update subnet status when dhcp lease file is changed
  pkg/subnet/dhcpserver/dnsmasq.go
Labels: release/bug

#110 v0.4.3
  VERSION
  chart/Chart.yaml
Labels: release/none

#113 helm value support nodeName
  chart/templates/deployment.yaml
  chart/values.yaml
Labels: enhancement, release/none

#123 robot updates Golang Version to 1.24.3
  .github/workflows/call-e2e.yaml
  .github/workflows/lint-golang.yaml
  GO_VERSION
  go.mod
  image/topohub/Dockerfile
Labels: pr/robot_update

#126 add BindingIP mac check
  pkg/webhook/bindingip/webhook.go
Labels: release/bug
