Repository infrastructure-io/topohub, pull requests merged in 2025-03, with the labels that each got.

#73 crd changed: show information
  chart/crds/topohub.infrastructure.io_hoststatuses.yaml
  doc/usage/node.md
  pkg/k8s/apis/topohub.infrastructure.io/v1beta1/hoststatus_types.go
  pkg/k8s/apis/topohub.infrastructure.io/v1beta1/subnet_types.go
Labels: release/feature-new

#85 robot updates Golang Version to 1.24.1
  .github/workflows/lint-golang.yaml
  GO_VERSION
  go.mod
  image/topohub/Dockerfile
Labels: pr/robot_update

#92 remove invalid code
  pkg/subnet/dhcpserver/UpdateSubnet.go
Labels: release/none

#82 fix: it takes long to synchronize hoststatus when lots of hostendpoints are created
  pkg/hoststatus/HostStatusReconcile.go
  pkg/hoststatus/manager.go
  pkg/lock/lockByID.go
  pkg/lock/lockByID_test.go
Labels: release/bug

#97 ztp
  chart/templates/configmap-dhcp.yaml
  doc/usage/ztp.md
Labels: release/feature-new
