Repository infrastructure-io/topohub, pull requests merged in 2025-06, with the labels that each got.

#139 robot updates Golang Version to 1.24.4
  .github/workflows/call-e2e.yaml
  .github/workflows/lint-golang.yaml
  GO_VERSION
  go.mod
  image/topohub/Dockerfile
Labels: pr/robot_update

#143 Fix DHCP assigned IP binding not work
  chart/templates/configmap-dhcp.yaml
  pkg/subnet/dhcpserver/config.go
Labels: release/bug

#144 Resolve the occasional failure issue with PXE installation on Lenovo servers
  pkg/redfish/power.go
Labels: release/bug

#146 update golang version ci schedule
  .github/workflows/update-golang.yaml
Labels: release/none

#148 Update SSH status type and ensure it is consistent with Redfish
  pkg/sshstatus/ssh_status_reconcile.go
Labels: bug, release/bug

#154 Some servers do not support the SimpleStorage interface
  pkg/redfish/getinfo.go
Labels: release/bug
