Repository infrastructure-io/topohub, pull requests merged in 2025-08, with the labels that each got.

#168 fix pxe bootOverride error
  pkg/redfish/power.go
Labels: release/bug, cherrypick-release-v0.5

#171 support dhcp create hostendpoint
  chart/crds/topohub.infrastructure.io_redfishstatuses.yaml
  chart/crds/topohub.infrastructure.io_sshstatuses.yaml
  doc/usage/node.md
  go.mod
  pkg/hostendpoint/controller.go
  pkg/hostoperation/controller.go
  pkg/k8s/apis/topohub.infrastructure.io/v1beta1/constants.go
  pkg/k8s/apis/topohub.infrastructure.io/v1beta1/redfishstatus_types.go
  pkg/k8s/apis/topohub.infrastructure.io/v1beta1/sshstatus_types.go
  pkg/k8s/apis/topohub.infrastructure.io/v1beta1/zz_generated.deepcopy.go
  pkg/redfish/interface.go
  pkg/redfishstatus/data/cache.go
  pkg/redfishstatus/dhcp.go
  pkg/redfishstatus/manager.go
  pkg/redfishstatus/redfish_status_reconcile.go
  pkg/redfishstatus/tools.go
  pkg/secret/controller.go
  pkg/sshstatus/data/cache.go
  pkg/sshstatus/ssh/client.go
  pkg/sshstatus/ssh_status_reconcile.go
  pkg/sshstatus/tools.go
  pkg/tools/tools.go
  pkg/tools/tools_test.go
  pkg/webhook/hostendpoint/webhook.go
  pkg/webhook/redfishstatus/webhook.go
  pkg/webhook/sshstatus/webhook.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_custom.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_default.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_fail.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/interceptor/intercept.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/objectutil.go
Labels: release/feature-new

#178 Add session pool to support connection reuse
  .github/workflows/lint-golang.yaml
  .vscode/settings.json
  cmd/topohub/main.go
  doc/design/session-pool/README.md
  go.mod
  go.sum
  pkg/clients/pool/fake.go
  pkg/clients/pool/option.go
  pkg/clients/pool/option_test.go
  pkg/clients/pool/pool.go
  pkg/clients/pool/pool_test.go
  pkg/clients/pool/session.go
  pkg/clients/pool/session_test.go
  pkg/clients/redfish/client.go
  pkg/clients/redfish/getinfo.go
  pkg/clients/redfish/log.go
  pkg/clients/redfish/power.go
  pkg/clients/redfish/session.go
  pkg/clients/redfish/session_test.go
  pkg/clients/redfish/snmp.go
  pkg/clients/ssh/client.go
  pkg/clients/ssh/session.go
  pkg/clients/ssh/session_test.go
  pkg/log/log.go
  vendor/github.com/agiledragon/gomonkey/v2/.gitignore
  vendor/github.com/agiledragon/gomonkey/v2/LICENSE
  vendor/github.com/agiledragon/gomonkey/v2/Makefile
  vendor/github.com/agiledragon/gomonkey/v2/README.md
  vendor/github.com/agiledragon/gomonkey/v2/creflect/ae1.17.go
  vendor/github.com/agiledragon/gomonkey/v2/creflect/be1.16.go
  vendor/github.com/agiledragon/gomonkey/v2/creflect/type.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_386.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_amd64.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_arm64.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_loong64.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_riscv64.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_darwin.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_linux.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_windows.go
  vendor/github.com/agiledragon/gomonkey/v2/patch.go
  vendor/github.com/agiledragon/gomonkey/v2/ut.sh
  vendor/github.com/agiledragon/gomonkey/v2/write_darwin_amd64.s
  vendor/github.com/agiledragon/gomonkey/v2/write_darwin_arm64.s
  vendor/modules.txt
Labels: release/feature-new

#179 Redfish status data updates every minute, info data updates every day
  chart/templates/configmap-feature.yaml
  chart/values.yaml
  doc/usage/node.md
  pkg/config/config.go
  pkg/redfish/getinfo.go
  pkg/redfish/interface.go
  pkg/redfishstatus/redfish_status_reconcile.go
Labels: release/feature-new

#182 Accessing SSH client using the session pool
  cmd/topohub/main.go
  pkg/clients/redfish/client.go
  pkg/clients/redfish/pool.go
  pkg/clients/redfish/session.go
  pkg/clients/ssh/client.go
  pkg/clients/ssh/pool.go
  pkg/clients/ssh/session.go
  pkg/sshstatus/data/cache.go
  pkg/sshstatus/manager.go
  pkg/sshstatus/ssh/client.go
  pkg/sshstatus/ssh_status_reconcile.go
  pkg/tools/tools.go
  pkg/tools/tools_test.go
Labels: release/feature-new

#184 Add scripts support to build the test chart
  scripts/ci_to_dev.sh
  scripts/common.sh
  scripts/run_with_container.sh
Labels: release/feature-new

#185 Accessing redfish client using the session pool
  pkg/clients/pool/pool.go
  pkg/clients/redfish/client.go
  pkg/clients/redfish/getinfo.go
  pkg/clients/redfish/log.go
  pkg/clients/redfish/pool.go
  pkg/clients/redfish/power.go
  pkg/clients/redfish/session.go
  pkg/clients/redfish/session_test.go
  pkg/clients/redfish/snmp.go
  pkg/clients/ssh/session.go
  pkg/clients/ssh/session_test.go
  pkg/hostoperation/controller.go
  pkg/redfish/getinfo.go
  pkg/redfish/interface.go
  pkg/redfish/log.go
  pkg/redfish/power.go
  pkg/redfish/snmp.go
  pkg/redfishstatus/data/cache.go
  pkg/redfishstatus/manager.go
  pkg/redfishstatus/redfish_status_reconcile.go
  pkg/sshstatus/ssh_status_reconcile.go
Labels: release/feature-new

#189 Fixed the host health check issue
  pkg/redfishstatus/redfish_status_reconcile.go
  pkg/sshstatus/ssh_status_reconcile.go
Labels: release/bug

#191 update deployment affinity
  chart/README.md
  chart/templates/deployment.yaml
  chart/values.schema.json
  chart/values.yaml
Labels: release/bug

#192 fix update subnet not work
  pkg/subnet/dhcpserver/dnsmasq.go
  pkg/subnet/dhcpserver/manager.go
  pkg/subnet/manager.go
Labels: release/bug

#193 v0.6.0
  VERSION
  chart/Chart.yaml
Labels: release/none

#196 Optimizing lock and memory usage during redfish status reconcile
  pkg/lock/lock_by_id.go
  pkg/lock/lock_fast.go
  pkg/redfishstatus/manager.go
  pkg/redfishstatus/redfish_status_reconcile.go
Labels: release/feature-new
